version: '3'
networks:
  Tour:
    driver: bridge
services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "9000:9000"
    container_name: php
    networks:
      - Tour
  web:
    image: nginx:latest
    container_name: tour-nginx
    ports:
      - "0.0.0.0:80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - Tour
